[package]
name = "synch"
version = "0.1.0"
edition = "2021"

[dependencies]
crdts = "7.3.2"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
webrtc = "0.11.0"
ciborium = "0.2.2"
anyhow = "1.0.86"
tokio = { version = "1", features = ["full"] }
base64 = "0.22.1"